### PR TITLE
Fix covers rule for functions.

### LINKED ISSUE #143: @coverage annotation for function outside class
Hi!

With an update to `1.2.1` I get a new error reported regarding my `@coverage` annotation. The coverage is reported correctly for this function, however PHPStan tells me the annotation is incorrect.

image

Functions file:
```php
<?php

declare(strict_types=1);

namespace Domain\Shared\Translation;

/**
 * @param array<mixed> $parameters
 */
function t(string $message, array $parameters = [], string $domain = null): TranslatableMessage {}
```

Test class:

```php
<?php

declare(strict_types=1);

namespace Tests\Unit\Domain\Shared\Translation;

use Tests\Unit\UnitTestCase;

use function Domain\Shared\Translation\t;

/**
 * @covers \Domain\Shared\Translation\t
 */
class FunctionsTest extends UnitTestCase
{}
```

`composer.json`:
```
{
    "autoload": {
        "files": [
            "src/Domain/Shared/Translation/functions.php"
        ],
        "psr-4": {
            "Application\\": "src/Application",
            "Domain\\": "src/Domain",
            "Infrastructure\\": "src/Infrastructure",
            "UserInterface\\": "src/UserInterface"
        }
    },
}

### PR DESCRIPTION
**Pull request by mad-briller**
resolves: https://github.com/phpstan/phpstan-phpunit/issues/143

### CODE REVIEW

File: tests/Rules/PHPUnit/ClassMethodCoversExistsRuleTest.php [hunk 1]
```diff
@@ -26,15 +26,15 @@ public function testRule(): void
 	{
 		$this->analyse([__DIR__ . '/data/method-coverage.php'], [
 			[
-				'@covers value ::ignoreThis references an invalid class.',
+				'@covers value ::ignoreThis references an invalid method.',
```
Comment (mad-briller) [inline tests/Rules/PHPUnit/ClassMethodCoversExistsRuleTest.php]: these cases changed because the messaging was refined to indicate it's a method if `::` is found in the `@covers` annotation,

previously it would say `class` in all cases which was a little misleading

File: src/Rules/PHPUnit/CoversHelper.php [hunk 2]
```diff
@@ -83,16 +85,22 @@ public function processCovers(
...
+			if (!isset($method) && $this->reflectionProvider->hasFunction(new Name($covers, []), null)) {
+				return $errors;
+			}
+
 			$errors[] = RuleErrorBuilder::message(sprintf(
-				'@covers value %s references an invalid class.',
-				$covers
+				'@covers value %s references an invalid %s.',
+				$covers,
+				$isMethod ? 'method' : 'class or function'
```
Comment (ondrejmirtes) [inline src/Rules/PHPUnit/CoversHelper.php:105]: I don't see any test for "class or function", can you find it or add it?

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]

File: src/Rules/PHPUnit/CoversHelper.php (hunk 2 above)
Comment (mad-briller) [reply src/Rules/PHPUnit/CoversHelper.php:105]: good spot, i've added that now

File: tests/Rules/PHPUnit/ClassMethodCoversExistsRuleTest.php (hunk 1 above)
Comment (ondrejmirtes) [reply tests/Rules/PHPUnit/ClassMethodCoversExistsRuleTest.php]: What would be great is to add the nonexistent names to all these messages. Be as explicit as possible 😊

Comment (mad-briller) [reply tests/Rules/PHPUnit/ClassMethodCoversExistsRuleTest.php]: as in the fully qualified name? i did consider adding that but didn't want to change too much at once!

Comment (ondrejmirtes) [reply tests/Rules/PHPUnit/ClassMethodCoversExistsRuleTest.php]: You can change it, it's in bleedingEdge 😊

**Review by ondrejmirtes — APPROVED** [review]

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by darthf1** [comment]
Awesome, that's quick. Thank you @mad-briller and @ondrejmirtes
